json-config: Still erroring out
On client, to dedicated server, fatal error on connect:

[17:36:07] [Netty Client IO #1/ERROR]: SimpleChannelHandlerWrapper exception
java.lang.NoSuchMethodError: net.minecraft.client.Minecraft.getMinecraft()Lnet/minecraft/client/Minecraft;
	at subaraki.paintings.mod.network.PaintingsMessage$Handler.onMessage(PaintingsMessage.java:75) ~[PaintingsMessage$Handler.class:?]
	at subaraki.paintings.mod.network.PaintingsMessage$Handler.onMessage(PaintingsMessage.java:66) ~[PaintingsMessage$Handler.class:?]

Added a "missing.png" for future use as a placeholder image.